### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by bryanwillis** [tjluoma/hazel-newvolume#1]
Is this rule/script available? I downloaded it, but noticing there is no rule or shell script included. Would love to use this!

**Comment by tjluoma** [comment]
You're right, somehow the Hazel rule didn't get included in this, which makes the whole thing a little useless. Will track it down and add it.

**Comment by tjluoma** [comment]
For some reason the comment seems to be missing (or I'm just not seeing it?):

> Is this rule/script available? I downloaded it, but noticing there is no rule or shell script included. Would love to use this!
>

**Comment by PaulCapestany** [comment]
+1 to see `hazel-newvolume.sh` script if possible :)

**Comment by bryanwillis** [comment]
ha thanks @tjluoma

**Comment by timmerk** [comment]
Bump

**Comment by tjluoma** [comment]
Cripes, I can't believe I forgot this. It's there now. Sorry for the delay.

**Comment by bryanwillis** [comment]
thanks 👍
